#goal definition
bool execute
---
#result definition
bool result
---
#feedback
string prev_state
string state

# NOTE: package and cmake are not changed yet since this will be going to common or extern anyways
