##########################################
#
# Arm Movement data
#
##########################################

# Action to be performed, either joint, coords, open, close
#joint: moves the arm with joint positions
#coords: moves the arm with cartesian positions
#open: open the Hand
#close: closes the hand
String action

#Coords or joints 6 int
int32 a
int32 b
int32 c
int32 d 
int32 e
int32 f 
int32 g
int32 h
